# Generated by Django 5.2.8 on 2026-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('domaine_d_interet', models.CharField(blank=True, max_length=200, null=True, verbose_name="Domaine d'interêt")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Signature de la pétition ',
                'verbose_name_plural': 'Signatures de la pétition',
                'ordering': ['-created_at'],
            },
        ),
    ]
