# Generated by Django 5.2.8 on 2026-01-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='nom_complet',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='petition',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='petition',
            name='niveau_soutien',
            field=models.IntegerField(choices=[(1, '1 - Très faible'), (2, '2 - Faible'), (3, '3 - Moyen'), (4, '4 - Bon'), (5, '5 - Excellent')], default=1, verbose_name='Niveau de soutien'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='nom',
            field=models.CharField(default=125, max_length=200, verbose_name='Nom complet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='telephone',
            field=models.CharField(default=91271004, max_length=20, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
