# Generated by Django 5.2.8 on 2026-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_rename_nom_complet_petition_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='signature',
            field=models.ImageField(default=1, upload_to='petition_signature/', verbose_name='Signature électronique'),
            preserve_default=False,
        ),
    ]
