# Generated by Django 6.0.1 on 2026-01-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_petition_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='niveau_soutien',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Très faible'), (2, '2 - Faible'), (3, '3 - Moyen'), (4, '4 - Bon'), (5, '5 - Excellent')], null=True, verbose_name='Niveau de soutien'),
        ),
    ]
