# Generated by Django 6.0.1 on 2026-01-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_alter_petition_niveau_soutien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
    ]
